# name: Deploy with Ansible

# on:
#   workflow_dispatch:

# env:
#   DOCKER_IMAGE: triplee1/simplifiedai

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout source code
#         uses: actions/checkout@v4

#       - name: Install Ansible
#         run: |
#           sudo apt update
#           sudo apt install -y ansible

#       - name: Set up SSH key
#         uses: webfactory/ssh-agent@v0.5.0
#         with:
#           ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

#       - name: Add host key to known hosts
#         run: |
#           mkdir -p ~/.ssh
#           ssh-keyscan ${{ secrets.VIRTUAL_MACHINE_IP }} >> ~/.ssh/known_hosts

#       - name: Create Ansible inventory
#         run: |
#           echo "[linode]" > inventory.ini
#           echo "${{ secrets.VIRTUAL_MACHINE_IP }} ansible_user=root" >> inventory.ini

#       - name: Create .env file
#         run: |
#           cat << EOF > .env
#           DATABASE_URL=${{ secrets.DATABASE_URL }}
#           DOCKERHUB_TOKEN=${{ secrets.DOCKERHUB_TOKEN }}
#           DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}
#           OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
#           EOF

#       - name: Create Ansible Vars file
#         run: |
#           mkdir -p devops
#           cat << EOF > devops/vars.yaml
#           dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
#           dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
#           EOF

#       - name: Run Ansible playbook
#         env:
#           ANSIBLE_HOST_KEY_CHECKING: false
#         run: |
#           ansible-playbook -i inventory.ini devops/playbook.yaml

#       - name: Remove vars file
#         run: rm -f devops/vars.yaml && .env
#         if: always()
